In [30]:
a = np.array([1,2,3,4,5], dtype='int16')
print(a)

[1 2 3 4 5]


In [31]:
b = np.array ([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [32]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [33]:
# Get shape
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [34]:
print(a.dtype)
print(b.dtype)
print(a.itemsize)

int16
int64
2


In [35]:
# Get a specific element [r, c]
print(b[1, 2])

6


In [36]:
# Get a specific row and column
print(b[0, :])
print(b[:,1])

[1 2 3]
[2 5]


In [ ]:
# [Startindex:endindex:stepsize]
print(a[0:4:2])
print(b[0:2, 0:3:2])

[1 3]
[[1 3]
 [4 6]]


In [39]:
b[1,2] = 20
print(b)

[[ 1  2  3]
 [ 4  5 20]]


In [45]:
b[0:2,1] = [1,2]
print(b)

[[1 1 1]
 [4 2 2]]


In [46]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

3


In [48]:
print(c[0,1,1])

4


In [56]:
print(c[1,0:2,0:1:2])

[[5]
 [7]]


In [74]:
c[1,1,0] = 6
print(c)

[[[1 2]
  [5 5]]

 [[5 6]
  [6 5]]]


In [80]:
# All 0s matrix
print(np.zeros((2,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# All 1s matrix
print(np.ones((4,2,3)))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [82]:
#Any other number
print(np.full((2,3,4), 99))

[[[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]

 [[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]]


In [84]:
#Any other number (full_like)
print(np.full_like(c, 4))

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]


In [85]:
# Random deimal numbers
print(np.random.rand(4,2))

[[0.24888496 0.19393441]
 [0.17667567 0.1482098 ]
 [0.63241673 0.78320677]
 [0.09801375 0.94891241]]


In [88]:
print(np.random.random_sample(c.shape))

[[[0.7012651  0.15355971]
  [0.22965936 0.35614754]]

 [[0.0630914  0.65471062]
  [0.17856804 0.77556033]]]


In [97]:
#Random Integer Values
print(np.random.randint(4,7, size=(3,3)))

[[5 6 4]
 [5 5 4]
 [4 6 4]]


In [98]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [99]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [101]:
output[1:4, 1:4] = 0
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [104]:
#Be careful when copying arrays
d = np.array([1,2,3])
e = d.copy()
e[2] = 100
print(e)
print(d)


[  1   2 100]
[1 2 3]


In [107]:
#Math
print(d+2)
print(d-2)
print(d*2)
print(d/2)
print(d + e)
print(np.sin(d))
print(np.cos(d))




[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[  2   4 103]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [108]:
#Linear Algebra
a = np.full((2,3), 1)
b = np.full((3,2), 2)
print(a)
print(b)

print(np.matmul(a,b))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [109]:
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [110]:
#Statistics
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [118]:
print(np.min(stats))
print(np.max(stats))
print(np.min(stats, axis=1))
print(np.max(stats, axis=1))
print(np.sum(stats))
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))

1
6
[1 4]
[3 6]
21
[5 7 9]
[ 6 15]


In [120]:
# Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
after2 = before.reshape((8,1))
print(after)
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2, v1,v2]))

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [123]:
#Horizantal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack((h1,h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [ ]:
#Load Data from File
data = np.genfromtxt('data.txt', delimiter=',')
print(data)

# to get as int
data = data.astype('int32')
print(data)

In [ ]:
#Advanced Indexing and Boolean Masking
#sets file data to true if >50 else false
print(data > 50)
# Only displays values > 50
print(data[data > 50])



In [124]:
#You can index with alist in NumPy
a = np.array([1,2,3,4,5, 6, 7, 8, 9])
print(a[[1,2,8]])


[2 3 9]


In [ ]:
#If we looked downnwards at columns, are any values > 50
print(np.any(data > 50, axis=0))
# IF we looked downards at columns, are all values > 50
print(np.all(data > 50, axis=0))
# if axis = 1, we are looking at rows

In [ ]:
print((data > 50) & (data < 100))